# Generated by Django 5.0.1 on 2026-02-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
